config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:show, :create]

  resources :users, only: [:index, :create, :score] do
    get 'score', on: :member
  end

  root to: "users#index"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  def self.calculate_weights
    sum(:weighted_value)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  def self.available
    pluck(:id)
  end

  def next
    self.class.where("id > ?", id).first
  end

  def first?
    self == self.class.first
  end

  def last?
    self.next.nil?
  end
end

app/models/survey.rb
class Survey <ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  belongs_to :answer
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :surveys
  has_many :answers, through: :surveys

  scope :with_score, -> { where("score is not null") }
  scope :ordered, -> { order('score desc') }

  def calculate_score
    answers.calculate_weights
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_user
  before_action :get_question
  before_action :validate_session, unless: proc { session[:stopped] }

  def create
    @user.surveys.create!(question: @question, answer_id: params[:answer_id])

    if @question.last?
      session[:stopped] = Time.now
      redirect_to score_user_path(@user)
    else
      session[:current_question_id] = @question.next.id
      redirect_to question_path(@question.next.id)
    end
  end

  private

  def get_user
    @user = User.find(session[:user_id])
  end

  def get_question
    @question = Question.find(params[:id])
  end

  def validate_session
    current_question_id = session[:current_question_id]

    if @user.blank?
      redirect_to root_path and return
    elsif current_question_id && current_question_id != @question.id
      redirect_to question_path(current_question_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    reset_session
    @user  = User.new
    @users = User.with_score.ordered
  end

  def create
    @user = User.create!(name: params[:user][:name])
    set_sessions(@user)
    redirect_to question_path(Question.first)
  end

  def score
    @user = User.find(session[:user_id])
    @user.update_column(:score, @user.calculate_score)
    @total_time = calculate_session_time
  end

  private

  def calculate_session_time
    diff_in_seconds = session[:stopped].to_time - session[:started].to_time
    elapsed_time = Time.at(diff_in_seconds).utc.strftime("%H:%M:%S")
  end

  def set_sessions(user)
    session[:user_id] = user.id
    session[:started] = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<section class="content">
  <%= yield %>
</section>

</body>
</html>

app/views/questions/show.html.erb
<h1 class="bordered"><%= @user.name %></h1>

<h3><%= @question.content %></h3>

<%= form_tag questions_path do |f| %>
    <% @question.answers.each do |answer| %>
        <p>
          <%= radio_button_tag :answer_id, answer.id, false, class: "answer" %>
          <%= answer.content %>
        </p>
    <% end %>

    <%= hidden_field_tag :id, @question.id %>
    <%= submit_tag "Volgende", class: "next-btn" %>
<% end %>

app/views/users/index.html.erb
<%= form_for @user do |f| %>
    <p>
      Wat is je naam?<br>
      <%= f.text_field :name %>
    </p>
    <p><%= f.submit "Start Quiz" %></p>
<% end %>

<% if @users.present? %>
    <hr>

    <h1>Highscores</h1>
    <ul>
      <% @users.each do |u| %>
          <li><%= u.name %> <%= u.score %></li>
      <% end %>
    </ul>
<% end %>

app/views/users/score.html.erb
<h1>
  <%= @user.name %>, je score is:
  <%= @user.score %>.
  Je tijd: <%= @total_time %>
</h1>

<%= link_to "Afsluiten", root_path, class:"reset" %>